<<<<<<< HEAD
/* XML text for generating workspace and toolbox */
function generateWorkspaceXML(nLeds) {
	var workspaceXML = '<xml>';
	workspaceXML += '<block type="run_on_start" id="5CvAS;1lmZM1aL{c:g_(" x="13" y="12">';
	workspaceXML += '<field name="BRIGHTNESS">'+ DEFAULT_BRIGHTNESS +'</field>';
	workspaceXML += '<field name="PIN">'+ DEFAULT_PIN +'</field>';
	workspaceXML += '<field name="NLEDS">' + nLeds + '</field>';
	workspaceXML += '</block>';
	workspaceXML += '<block type="run_repeatedly" id="24y33Lz0II_Z)t7nfY1[" x="13" y="140"></block>';
	workspaceXML += '</xml>';
	return workspaceXML;
};  

MAX_BLOCK_LENGTH = 20;
function generateToolboxXML(nLeds) {
	var toolbox = '<xml>\n';
	toolbox += '  <category name="Colors/Patterns" colour="#a55b6d">\n';
	if (nLeds < MAX_BLOCK_LENGTH) {
		toolbox += '    <block type="color_led">\n';
		for (var i = 0; i < nLeds; i++) {
			var fieldDef = '      <field name="C' + (i+1).toString() + '">' + defaultColorFromList(i) + '</field>\n';
			toolbox += fieldDef;
		}
		toolbox += '   </block>\n';
	}
	toolbox += '    <block type="single_color_led">\n';
	toolbox += '      <field name="C1">#ff0000</field>\n';
	toolbox += '    </block>\n';
	toolbox += '    <block type="color_wheel_value">\n';
	toolbox += '     <field name="WHEEL_ANGLE">0</field>\n';
	toolbox += '    </block>\n';
	toolbox += '    <block type="random_color"></block>\n';
	toolbox += '	<block type="rainbow_led"></block>\n';
	toolbox += '    <block type="repeat_pattern">\n';
	toolbox += '	  <value name="PATTERN">\n';
	toolbox += '	  <block type = "variable_color_list">\n';
	toolbox += '	     <value name="ADD0">\n';
	toolbox += '	       <block type="single_color_led">\n';
	toolbox += '		     <field name="C1">#000000</field>\n';
	toolbox += '		   </block>\n';
	toolbox += '		 </value>\n';
	toolbox += '		 <value name="ADD1">\n';
	toolbox += '		 <block type="single_color_led">\n';
	toolbox += '		   <field name="C1">#ff0000</field>\n';
	toolbox += '		 </block>\n';
	toolbox += '		 </value>\n';
	toolbox += '	  </block>\n';
	toolbox += '	  </value>\n';
	toolbox += '    </block>\n';
    if (nLeds < MAX_BLOCK_LENGTH) {
		toolbox += '    <block type="color_led_expanded"></block>\n';
		toolbox += '    <block type="change_to">\n';
		toolbox += '      <value name="COLOR_LIST">\n';
		toolbox += '        <shadow type="single_color_led">\n';
		toolbox += '          <field name="C1">#000000</field>\n';
		toolbox += '        </shadow>\n';
		toolbox += '      </value>\n';
		toolbox += '    </block>\n';
	}
	if (nLeds < MAX_BLOCK_LENGTH) {
		toolbox += '    <block type="change_to">\n';
		toolbox += '      <value name="COLOR_LIST">\n';
		toolbox += '        <block type="color_led">\n';
		for (var i = 0; i < nLeds; i++) {
			var fieldDef = '      <field name="C' + (i+1).toString() + '">' + defaultColorFromList(i) + '</field>\n';
			toolbox += fieldDef;
		}
		toolbox += '        </block>\n';
		toolbox += '      </value>\n';
		toolbox += '    </block>\n';
	}
	toolbox += '    <block type="change_to"></block>\n';
	toolbox += '    <block type="set_led_at">\n';
	toolbox += '      <field name="LED_INDEX">1</field>\n';
	toolbox += '      <value name="COLOR_VALUE">\n';
	toolbox += '        <shadow type="single_color_led">\n';
	toolbox += '          <field name="C1">#ff0000</field>\n';
	toolbox += '        </shadow>\n';
	toolbox += '      </value>\n';
	toolbox += '      <field name="NAME">SHOW_NOW</field>\n';
	toolbox += '    </block>\n';
	toolbox += '  </category>\n';
	toolbox += '  <category name="Animations" colour="#a5a55b">\n';
	toolbox += '    <block type="block_wait">\n';
	toolbox += '      <field name="WAIT_SEC">0.5</field>\n';
	toolbox += '   </block>\n';
	toolbox += '    <block type="rotate_leds">\n';
	toolbox += '      <field name="ROTATION_AMT">1</field>\n';
	toolbox += '    </block>\n';
	toolbox += '    <block type="shift_leds">\n';
	toolbox += '      <field name="SHIFT_AMT">1</field>\n';
	toolbox += '    </block>\n';
	toolbox += '    <block type="smooth_change_to">\n';
	toolbox += '      <field name="speed">SLOW</field>\n';
	toolbox += '      <value name="COLOR_LIST">\n';
    if (nLeds < MAX_BLOCK_LENGTH) {
		toolbox += '        <shadow type="color_led">\n';
		for (var i = 0; i < nLeds; i++) {
			var fieldDef = '      <field name="C' + (i+1).toString() + '">' + defaultColorFromList(i) + '</field>\n';
			toolbox += fieldDef;
		}
		toolbox += '        </shadow>\n';
	} else {
		toolbox += '        <shadow type="single_color_led">\n'
		toolbox += '          <field name="C1">#cc33cc</field>\n';
		toolbox += '	    </shadow>\n';
	}
	toolbox += '      </value>\n';
	toolbox += '    </block>\n';
	toolbox += '    <block type="wipe_color">\n';
	toolbox += '       <value name="COLOR_LIST">\n';
	toolbox += '	     <shadow type="single_color_led">\n';
	toolbox += '		   <field name="C1">#cc33cc</field>\n';
	toolbox += '	    </shadow>\n';
	toolbox += '      </value>\n';
	toolbox += '      <field name="DIRECTION">LOW_TO_HIGH</field>\n';
	toolbox += '      <field name="SPEED">SLOW</field>\n';
	toolbox += '    </block>\n';
	toolbox += '    <block type="twinkle">\n';
	toolbox += '      <field name="nleds">3</field>\n';
	toolbox += '      <field name="nseconds">5</field>\n';
	toolbox += '	  <value name="COLOR_LIST">\n';
	toolbox += '	  <block type = "variable_color_list">\n';
	toolbox += '	     <value name="ADD0">\n';
	toolbox += '	       <block type="single_color_led">\n';
	toolbox += '		     <field name="C1">#cc33cc</field>\n';
	toolbox += '		   </block>\n';
	toolbox += '		 </value>\n';
	toolbox += '		 <value name="ADD1">\n';
	toolbox += '		 <block type="single_color_led">\n';
	toolbox += '		   <field name="C1">#33ccff</field>\n';
	toolbox += '		 </block>\n';
	toolbox += '		 </value>\n';
	toolbox += '	  </block>\n';
	toolbox += '	  </value>\n';
	toolbox += '    </block>\n';
	toolbox += '	<block type="morse">';
	toolbox += '      <field name="MORSE_TEXT">HELLO</field>';
	toolbox += '      <field name="SPEED">SPEED_MEDIUM</field>';
	toolbox += '      <value name="TEXT_COLOR">';
	toolbox += '        <shadow type="single_color_led">';
	toolbox += '          <field name="C1">#ff0000</field>';
	toolbox += '        </shadow>';
	toolbox += '      </value>';
	toolbox += '    </block>';
	toolbox += '  </category>';
	toolbox += '  <category name="Loops" colour="#5ba55b">';
	toolbox += '    <block type="controls_repeat_ext">';
	toolbox += '      <value name="TIMES">';
	toolbox += '        <shadow type="math_number">';
	toolbox += '          <field name="NUM">10</field>';
	toolbox += '        </shadow>';
	toolbox += '      </value>';
	toolbox += '    </block>';
	toolbox += '    <block type="controls_for">';
	toolbox += '      <field name="VAR" id="/;]tS=r!DeDO/g6Is/th" variabletype="">i</field>';
	toolbox += '      <value name="FROM">';
	toolbox += '        <shadow type="math_number">';
	toolbox += '          <field name="NUM">1</field>';
	toolbox += '        </shadow>';
	toolbox += '      </value>';
	toolbox += '      <value name="TO">';
	toolbox += '        <shadow type="math_number">';
	toolbox += '          <field name="NUM">10</field>';
	toolbox += '        </shadow>';
	toolbox += '      </value>';
	toolbox += '      <value name="BY">';
	toolbox += '        <shadow type="math_number">';
	toolbox += '          <field name="NUM">1</field>';
	toolbox += '        </shadow>';
	toolbox += '      </value>';
	toolbox += '    </block>';
	toolbox += '  </category>';
	toolbox += '  <category name="Logic" colour="#5b80a5">';
	toolbox += '    <block type="controls_if"></block>';
	toolbox += '    <block type="logic_compare">';
	toolbox += '      <field name="OP">EQ</field>';
	toolbox += '    </block>';
	toolbox += '  </category>';
	toolbox += '  <category name="Math" colour="#5b5ba5">';
	toolbox += '    <block type="math_number">';
	toolbox += '      <field name="NUM">0</field>';
	toolbox += '    </block>';
	toolbox += '    <block type="math_arithmetic">';
	toolbox += '      <field name="OP">ADD</field>';
	toolbox += '      <value name="A">';
	toolbox += '        <shadow type="math_number">';
	toolbox += '          <field name="NUM">1</field>';
	toolbox += '        </shadow>';
	toolbox += '      </value>';
	toolbox += '      <value name="B">';
	toolbox += '        <shadow type="math_number">';
	toolbox += '          <field name="NUM">1</field>';
	toolbox += '        </shadow>';
	toolbox += '      </value>';
	toolbox += '    </block>';
	toolbox += '   <block type="math_random_int">';
	toolbox += '      <value name="FROM">';
	toolbox += '        <shadow type="math_number">';
	toolbox += '          <field name="NUM">0</field>';
	toolbox += '        </shadow>';
	toolbox += '      </value>';
	toolbox += '      <value name="TO">';
	toolbox += '        <shadow type="math_number">';
	toolbox += '          <field name="NUM">64</field>';
	toolbox += '        </shadow>';
	toolbox += '      </value>';
	toolbox += '    </block>';
	toolbox += '    <block type="math_modulo">';
	toolbox += '      <value name="DIVIDEND">';
	toolbox += '        <shadow type="math_number">';
	toolbox += '          <field name="NUM">100</field>';
	toolbox += '        </shadow>';
	toolbox += '      </value>';
	toolbox += '      <value name="DIVISOR">';
	toolbox += '        <shadow type="math_number">';
	toolbox += '         <field name="NUM">64</field>';
	toolbox += '       </shadow>';
	toolbox += '      </value>';
	toolbox += '    </block>';
	toolbox += '  </category>';
	toolbox += '  <category name="Variables" colour="#a55b5b" custom="VARIABLE"></category>';
	toolbox += '</xml>';	
	
	//console.log(toolbox);
	return toolbox;
};
=======
/* XML text for generating workspace and toolbox */
function generateWorkspaceXML(nLeds) {
	var workspaceXML = '<xml>';
	workspaceXML += '<block type="run_on_start" id="5CvAS;1lmZM1aL{c:g_(" x="13" y="12">';
	workspaceXML += '<field name="BRIGHTNESS">'+ DEFAULT_BRIGHTNESS +'</field>';
	workspaceXML += '<field name="PIN">'+ DEFAULT_PIN +'</field>';
	workspaceXML += '<field name="NLEDS">' + nLeds + '</field>';
	workspaceXML += '</block>';
	workspaceXML += '<block type="run_repeatedly" id="24y33Lz0II_Z)t7nfY1[" x="13" y="140"></block>';
	workspaceXML += '</xml>';
	return workspaceXML;
};  

function generateToolboxXML(nLeds) {
	var toolbox = '<xml>\n';
	toolbox += '  <category name="Colors/Patterns" colour="#a55b6d">\n';
	toolbox += '    <block type="color_led">\n';
	for (var i = 0; i < nLeds; i++) {
		var fieldDef = '      <field name="C' + (i+1).toString() + '">' + defaultColorFromList(i) + '</field>\n';
		toolbox += fieldDef;
	}
	toolbox += '   </block>\n';
	toolbox += '    <block type="single_color_led">\n';
	toolbox += '      <field name="C1">#ff0000</field>\n';
	toolbox += '    </block>\n';
	toolbox += '    <block type="color_wheel_value">\n';
	toolbox += '     <field name="WHEEL_ANGLE">0</field>\n';
	toolbox += '    </block>\n';
	toolbox += '    <block type="random_color"></block>\n';
	toolbox += '	<block type="rainbow_led"></block>\n';
	toolbox += '    <block type="repeat_pattern">\n';
	toolbox += '	  <value name="PATTERN">\n';
	toolbox += '	  <block type = "variable_color_list">\n';
	toolbox += '	     <value name="ADD0">\n';
	toolbox += '	       <block type="single_color_led">\n';
	toolbox += '		     <field name="C1">#000000</field>\n';
	toolbox += '		   </block>\n';
	toolbox += '		 </value>\n';
	toolbox += '		 <value name="ADD1">\n';
	toolbox += '		 <block type="single_color_led">\n';
	toolbox += '		   <field name="C1">#ff0000</field>\n';
	toolbox += '		 </block>\n';
	toolbox += '		 </value>\n';
	toolbox += '	  </block>\n';
	toolbox += '	  </value>\n';
	toolbox += '    </block>\n';
	toolbox += '    <block type="color_led_expanded"></block>\n';
	toolbox += '    <block type="change_to">\n';
	toolbox += '      <value name="COLOR_LIST">\n';
	toolbox += '        <shadow type="single_color_led">\n';
	toolbox += '          <field name="C1">#000000</field>\n';
	toolbox += '        </shadow>\n';
	toolbox += '      </value>\n';
	toolbox += '    </block>\n';
	toolbox += '    <block type="change_to">\n';
	toolbox += '      <value name="COLOR_LIST">\n';
	toolbox += '        <block type="color_led">\n';
	for (var i = 0; i < nLeds; i++) {
		var fieldDef = '      <field name="C' + (i+1).toString() + '">' + defaultColorFromList(i) + '</field>\n';
		toolbox += fieldDef;
	}
	toolbox += '        </block>\n';
	toolbox += '      </value>\n';
	toolbox += '    </block>\n';
	toolbox += '    <block type="change_to"></block>\n';
	toolbox += '    <block type="set_led_at">\n';
	toolbox += '      <field name="LED_INDEX">1</field>\n';
	toolbox += '      <value name="COLOR_VALUE">\n';
	toolbox += '        <shadow type="single_color_led">\n';
	toolbox += '          <field name="C1">#ff0000</field>\n';
	toolbox += '        </shadow>\n';
	toolbox += '      </value>\n';
	toolbox += '      <field name="NAME">SHOW_NOW</field>\n';
	toolbox += '    </block>\n';
	toolbox += '  </category>\n';
	toolbox += '  <category name="Animations" colour="#a5a55b">\n';
	toolbox += '    <block type="block_wait">\n';
	toolbox += '      <field name="WAIT_SEC">0.5</field>\n';
	toolbox += '   </block>\n';
	toolbox += '    <block type="rotate_leds">\n';
	toolbox += '      <field name="ROTATION_AMT">1</field>\n';
	toolbox += '    </block>\n';
	toolbox += '    <block type="shift_leds">\n';
	toolbox += '      <field name="SHIFT_AMT">1</field>\n';
	toolbox += '    </block>\n';
	toolbox += '    <block type="smooth_change_to">\n';
	toolbox += '      <field name="speed">SLOW</field>\n';
	toolbox += '      <value name="COLOR_LIST">\n';
	toolbox += '        <shadow type="color_led">\n';
	for (var i = 0; i < nLeds; i++) {
		var fieldDef = '      <field name="C' + (i+1).toString() + '">' + defaultColorFromList(i) + '</field>\n';
		toolbox += fieldDef;
	}
	toolbox += '        </shadow>\n';
	toolbox += '      </value>\n';
	toolbox += '    </block>\n';
	toolbox += '    <block type="wipe_color">\n';
	toolbox += '       <value name="COLOR_LIST">\n';
	toolbox += '	     <shadow type="single_color_led">\n';
	toolbox += '		   <field name="C1">#cc33cc</field>\n';
	toolbox += '	    </shadow>\n';
	toolbox += '      </value>\n';
	toolbox += '      <field name="DIRECTION">LOW_TO_HIGH</field>\n';
	toolbox += '      <field name="SPEED">SLOW</field>\n';
	toolbox += '    </block>\n';
	toolbox += '    <block type="twinkle">\n';
	toolbox += '      <field name="nleds">3</field>\n';
	toolbox += '      <field name="nseconds">5</field>\n';
	toolbox += '	  <value name="COLOR_LIST">\n';
	toolbox += '	  <block type = "variable_color_list">\n';
	toolbox += '	     <value name="ADD0">\n';
	toolbox += '	       <block type="single_color_led">\n';
	toolbox += '		     <field name="C1">#cc33cc</field>\n';
	toolbox += '		   </block>\n';
	toolbox += '		 </value>\n';
	toolbox += '		 <value name="ADD1">\n';
	toolbox += '		 <block type="single_color_led">\n';
	toolbox += '		   <field name="C1">#33ccff</field>\n';
	toolbox += '		 </block>\n';
	toolbox += '		 </value>\n';
	toolbox += '	  </block>\n';
	toolbox += '	  </value>\n';
	toolbox += '    </block>\n';
	toolbox += '	<block type="morse">';
	toolbox += '      <field name="MORSE_TEXT">HELLO</field>';
	toolbox += '      <field name="SPEED">SPEED_MEDIUM</field>';
	toolbox += '      <value name="TEXT_COLOR">';
	toolbox += '        <shadow type="single_color_led">';
	toolbox += '          <field name="C1">#ff0000</field>';
	toolbox += '        </shadow>';
	toolbox += '      </value>';
	toolbox += '    </block>';
	toolbox += '  </category>';
	toolbox += '  <category name="Loops" colour="#5ba55b">';
	toolbox += '    <block type="controls_repeat_ext">';
	toolbox += '      <value name="TIMES">';
	toolbox += '        <shadow type="math_number">';
	toolbox += '          <field name="NUM">10</field>';
	toolbox += '        </shadow>';
	toolbox += '      </value>';
	toolbox += '    </block>';
	toolbox += '    <block type="controls_for">';
	toolbox += '      <field name="VAR" id="/;]tS=r!DeDO/g6Is/th" variabletype="">i</field>';
	toolbox += '      <value name="FROM">';
	toolbox += '        <shadow type="math_number">';
	toolbox += '          <field name="NUM">1</field>';
	toolbox += '        </shadow>';
	toolbox += '      </value>';
	toolbox += '      <value name="TO">';
	toolbox += '        <shadow type="math_number">';
	toolbox += '          <field name="NUM">10</field>';
	toolbox += '        </shadow>';
	toolbox += '      </value>';
	toolbox += '      <value name="BY">';
	toolbox += '        <shadow type="math_number">';
	toolbox += '          <field name="NUM">1</field>';
	toolbox += '        </shadow>';
	toolbox += '      </value>';
	toolbox += '    </block>';
	toolbox += '  </category>';
	toolbox += '  <category name="Logic" colour="#5b80a5">';
	toolbox += '    <block type="controls_if"></block>';
	toolbox += '    <block type="logic_compare">';
	toolbox += '      <field name="OP">EQ</field>';
	toolbox += '    </block>';
	toolbox += '  </category>';
	toolbox += '  <category name="Math" colour="#5b5ba5">';
	toolbox += '    <block type="math_number">';
	toolbox += '      <field name="NUM">0</field>';
	toolbox += '    </block>';
	toolbox += '    <block type="math_arithmetic">';
	toolbox += '      <field name="OP">ADD</field>';
	toolbox += '      <value name="A">';
	toolbox += '        <shadow type="math_number">';
	toolbox += '          <field name="NUM">1</field>';
	toolbox += '        </shadow>';
	toolbox += '      </value>';
	toolbox += '      <value name="B">';
	toolbox += '        <shadow type="math_number">';
	toolbox += '          <field name="NUM">1</field>';
	toolbox += '        </shadow>';
	toolbox += '      </value>';
	toolbox += '    </block>';
	toolbox += '   <block type="math_random_int">';
	toolbox += '      <value name="FROM">';
	toolbox += '        <shadow type="math_number">';
	toolbox += '          <field name="NUM">0</field>';
	toolbox += '        </shadow>';
	toolbox += '      </value>';
	toolbox += '      <value name="TO">';
	toolbox += '        <shadow type="math_number">';
	toolbox += '          <field name="NUM">64</field>';
	toolbox += '        </shadow>';
	toolbox += '      </value>';
	toolbox += '    </block>';
	toolbox += '    <block type="math_modulo">';
	toolbox += '      <value name="DIVIDEND">';
	toolbox += '        <shadow type="math_number">';
	toolbox += '          <field name="NUM">100</field>';
	toolbox += '        </shadow>';
	toolbox += '      </value>';
	toolbox += '      <value name="DIVISOR">';
	toolbox += '        <shadow type="math_number">';
	toolbox += '         <field name="NUM">64</field>';
	toolbox += '       </shadow>';
	toolbox += '      </value>';
	toolbox += '    </block>';
	toolbox += '  </category>';
	toolbox += '  <category name="Variables" colour="#a55b5b" custom="VARIABLE"></category>';
	toolbox += '</xml>';	
	
	//console.log(toolbox);
	return toolbox;
};
>>>>>>> blockly-brightly/master
